name: dicee
description: A simple dice rolling Flutter app.

# Prevent publishing to pub.dev
publish_to: 'none'

# Version format: major.minor.patch+build
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS-style widgets
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # ✅ Recommended lint rules for Dart 3

flutter:
  uses-material-design: true

  assets:
    - images/dice1.png
    - images/dice2.png
    - images/dice3.png
    - images/dice4.png
    - images/dice5.png
    - images/dice6.png
